### PR TITLE
Make toolbar buttons vertical.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR orients the visualizer buttons vertically, and gets rid of the padidng at the top.

Before:
screen shot 2017-07-15 at 11 59 33 am

After:
screen shot 2017-07-15 at 11 59 20 am

One downside is that the buttons no longer move to fit in the window if the window is shrunk.

Before:
screen shot 2017-07-15 at 12 01 19 pm

After:
screen shot 2017-07-15 at 12 02 39 pm

### CODE REVIEW

**Comment by aymanhab** [comment]
I really like the vertical layout but the cutoff has been a concern since on smaller screens and eventually tablets keys may get cut. Since the buttons can easily be paired, can we try two columns layout?

**Comment by chrisdembia** [comment]
> can we try two columns layout?

Ah good idea; I will try that. We will probably need to keep iterating even after this gets merged.

**Comment by aseth1** [comment]
Could we also make the buttons smaller? They look massive!

**Comment by chrisdembia** [comment]
I'm pretty sure they look bigger because I made the browser window smaller than it would typically be. I am fine with making the buttons smaller but I would prefer to make that a separate PR.

**Comment by chrisdembia** [comment]
@aseth1 perhaps after this is merged, you could see what the buttons look like on your computer before we decide to make the buttons even smaller than @aymanhab did in his recent related PR?

**Comment by chrisdembia** [comment]
Okay I made some additional changes:

- Organized buttons into 3 columns and 4 rows
  - row 1: front, top, left
  - row 2: back, bottom, right
  - row 3: zoom in, zoom out, fit
  - row 4: screenshot, video
- Updated tooltip for "Fit" button to "Fit model(s) in visualizer window" (https://github.com/opensim-org/opensim-gui/issues/98)
- Made buttons smaller 
- Fixed non-transparent white corners of zoom-in and zoom-out buttons (I learned that this is really easy to do with Preview on Macs).

screen shot 2017-07-15 at 4 33 56 pm


Don't be alarmed by the large size of the buttons relative to the size of the screen; that is because I made my browser window small.

**Comment by chrisdembia** [comment]
I chose 3 columns rather than 2 because the 2-column layout did not result in the proper grouping of buttons.

**Comment by tkuchida** [comment]
Looks good! Perhaps "zoom out" should be to the *left* of "zoom in"?

**Comment by chrisdembia** [comment]
Sounds good. Anything else? We can also continue to iterate after ISB. I'm looking forward to new images for the buttons.

**Comment by aymanhab** [comment]
LGTM and the three columns could be rearranged later if needed. Feel free to merge after addressing feedback from @tkuchida Thanks @chrisdembia

**Comment by chrisdembia** [comment]
@tkuchida I've swapped zoom in and zoom out:

screen shot 2017-07-15 at 9 11 08 pm

**Comment by chrisdembia** [comment]
Merging. Thanks @aymanhab @tkuchida @aseth1

**Pull request merged**
