### PR TITLE
Loader compute vertex normals

### PR DESCRIPTION
**Pull request by aymanhab**
When loading meshes through json, call computevertexnormals to smooth out normals for later rendering

### CODE REVIEW

**Comment by aymanhab** [comment]
@tkuchida This PR places the call to computeVertexNormals in OpenSimLoader.js  Please let me know if this is in line with your local changes. Thanks

**Comment by aymanhab** [comment]
@tkuchida I don't think this is necessary for analytical shapes whose normals can be auto generated. We load lots of pathpoints, markers that are very small in size and I'd like to avoid as much overhead as possible loading them to reduce startup/loading time. Do you notice a difference in appearance of spheres or cylinders if you place the call as suggested in this PR? The three.js editor doesn't offer this option for analytical shapes but would be good to know. Thanks

**Comment by tkuchida** [comment]
I haven't investigated in detail, but spheres, etc. are ultimately meshes. My question has to do with performance, not appearance: I thought that computing vertex normals might reduce the workload of the shader downstream, but I don't know.

**Comment by aymanhab** [comment]
I stepped through the code for Sphere and the normals are precomputed indeed in the constructor.

**Comment by tkuchida** [comment]
> I stepped through the code for Sphere and the normals are precomputed indeed in the constructor.

Sounds good; I assume the same is true for other analytic geometry.

**Comment by aymanhab** [comment]
Thanks for the review @tkuchida Much appreciated 👍

**Pull request merged**
