### PR TITLE
New file for OpenSim watermark

### PR DESCRIPTION
**Pull request by aymanhab**
As suggested per Alpha feedback

### CODE REVIEW

**Comment by jenhicks** [comment]
@aymanhab I think it would be good to replicate the behavior of the current logo display. (1) it is a single color -- I believe gray and (2) I believe the color adapts based on what background is used. Is this something possible with three.js?

**Comment by chrisdembia** [comment]
> (2) I believe the color adapts based on what background is used.

Is this because it is transparent?

**Comment by aymanhab** [comment]
@jenhicks As it stands, the image is overlaid on top of the canvas so it's unlikely to know what's underneath. 
capturewatermark
An alternative, which is the longer term solution is to actually make the image part of the canvas (as a drawing rather than a transparent image) in that case we can either make sure it always appears regardless of background, or change the colors using threejs machinery. This could also take care of the issue where snapshots don't show the logo #97

**Comment by chrisdembia** [comment]
> issue number 97 (using # somehow points to three.js own issues not our fork's!)

:/ You'd have to give the full URL: https://github.com/opensim-org/opensim-gui/issues/97

**Pull request merged**
